import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Container, StoryCard, Text } from 'components'

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>DTI Pasikanan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Text size="3xl">Stories</Text>
        <div style={{ margin: '36px 0' }}>
          <StoryCard type="content" />
          <StoryCard type="content" />
          <StoryCard type="content" />
        </div>
      </Container>
    </>
  )
}

export default About
