import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { getSme } from 'utils/airtable'
import { ISme } from '@types'
import { GetServerSideProps } from 'next'

export const getServerSideProps: GetServerSideProps = async (context) => {
  const sme = JSON.parse(
    JSON.stringify(await getSme(context.query.id as string))
  )

  return {
    props: {
      sme,
    },
  }
}

interface IDirectoryContent {
  sme: ISme
}

const DirectoryContent = ({ sme }: IDirectoryContent) => {
  const { fields } = sme

  return (
    <div>
      <Head>
        <title>DTI Pasikanan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {fields.logo?.length > 0 && (
          <div
            style={{ height: '150px', width: '150px', position: 'relative' }}
          >
            <Image
              objectFit="contain"
              layout="fill"
              src={fields.logo[0].url}
              alt={fields.name}
            />
          </div>
        )}
        <h3 style={{ marginBottom: '0.5em' }}>{fields.name}</h3>
        <div style={{ marginBottom: '1em' }}>{fields.introduction}</div>
        <div style={{ marginBottom: '1em' }}>{fields.description}</div>
        <div style={{ marginBottom: '1em' }}>{fields.location}</div>
        <div style={{ marginBottom: '1em' }}>{fields.email}</div>
        <div style={{ marginBottom: '1em' }}>{fields.contactNumber}</div>
        <Link href="/directory">
          <a>
            <span style={{ textDecoration: 'underline' }}>
              Go back to directory list
            </span>
          </a>
        </Link>
      </main>
    </div>
  )
}

export default DirectoryContent
