import { GetStaticProps } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { ISme } from '@types'
import { getSmes } from 'utils/airtable'

export const getStaticProps: GetStaticProps = async () => {
  const smes = JSON.parse(JSON.stringify(await getSmes()))

  return {
    props: {
      smes,
    },
  }
}

interface IDirectory {
  smes: ISme[]
}

const Directory = ({ smes }: IDirectory) => {
  return (
    <div>
      <Head>
        <title>DTI Pasikanan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Link href="/">
          <a>
            <span style={{ textDecoration: 'underline' }}>
              Back to homepage
            </span>
          </a>
        </Link>
        <h3>SME Names here</h3>
        {smes.map((sme) => (
          <Link key={sme.id} href={`/directory/${sme.id}`}>
            <a>
              <span style={{ textDecoration: 'underline' }}>
                {sme.fields.name}
              </span>
            </a>
          </Link>
        ))}
      </main>
    </div>
  )
}

export default Directory
