import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Container, Text, YoutubeEmbed } from 'components'

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>DTI Pasikanan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <div style={{ margin: '36px 0' }}>
          <div style={{ marginBottom: '48px' }}>
            <Text size="2xl" style={{ fontWeight: 600 }}>
              What is Pasikatan?
            </Text>
          </div>
          <div style={{ marginTop: '24px' }}>
            <Text style={{ lineHeight: '32px' }}>
              Aliquam eu est lacus. Ut aliquam gravida turpis nec placerat.
              Integer egestas arcu rhoncus augue fermentum elementum. Nulla ac
              elit condimentum orci lacinia cursus. Phasellus eu placerat
              mauris. Vestibulum volutpat elementum enim quis elementum.
              Maecenas sem libero, efficitur et sagittis eu, condimentum id ex.
              In hac habitasse platea dictumst. Pellentesque lectus ex,
              malesuada finibus arcu vel, ornare lobortis libero. In sed enim
              mi.
            </Text>
          </div>
          <div style={{ marginTop: '24px' }}>
            <Text style={{ lineHeight: '32px' }}>
              Vestibulum ante ipsum primis in faucibus orci luctus et ultrices
              posuere cubilia curae; Cras sit amet facilisis ante, aliquet
              fermentum augue. Phasellus accumsan dapibus egestas. Morbi
              porttitor nulla vel metus ultricies ullamcorper. Lorem ipsum dolor
              sit amet, consectetur adipiscing elit. Curabitur ac orci eget dui
              finibus consectetur nec at lorem. Etiam pellentesque sollicitudin
              lorem quis consequat. Pellentesque eget nibh bibendum, volutpat
              dolor nec, ultricies felis. Aenean sit amet libero vitae purus
              pharetra tempor nec et dolor. Sed pulvinar finibus metus, nec
              bibendum mauris faucibus eu. Morbi tellus lectus, semper ac
              laoreet ut, fermentum a nulla. Proin sagittis purus est, non
              vulputate turpis fermentum in. Praesent aliquam lacinia accumsan.
            </Text>
          </div>
        </div>
        <h2 style={{ fontWeight: 600 }}>Resources</h2>
        <h3 style={{ fontWeight: 600, marginTop: '64px' }}>
          Coffeetable Books
        </h3>
        <div style={{ marginBottom: '12px' }}>
          <a
            href="https://drive.google.com/file/d/1SAaPwV-t46gT-rLbuIJSKYHMH6uYPlxA/view?usp=sharing"
            target="_blank"
            rel="noopener noreferrer"
            style={{
              color: 'aqua',
              textDecoration: 'underline',
            }}
          >
            <Text>Coffeetable Book Issue 1 - Spread 7-05-21</Text>
          </a>
        </div>
        <div style={{ marginBottom: '12px' }}>
          <a
            href="https://drive.google.com/file/d/1ivpFiJY3Si47T8KKw1OWQ8JTvX7KjhM7/view?usp=sharing"
            target="_blank"
            rel="noopener noreferrer"
            style={{
              color: 'aqua',
              textDecoration: 'underline',
            }}
          >
            <Text>Coffeetable Book Issue 1 - Spread 8-16-21</Text>
          </a>
        </div>
        <div>
          <a
            href="https://drive.google.com/file/d/1oJl00SGiNneE0UNWQU1suro9346yB9eU/view?usp=sharing"
            target="_blank"
            rel="noopener noreferrer"
            style={{
              color: 'aqua',
              textDecoration: 'underline',
            }}
          >
            <Text>Coffeetable Book Issue 2</Text>
          </a>
        </div>

        <h3 style={{ fontWeight: 600, marginTop: '64px' }}>Shows</h3>
        <div style={{ marginBottom: '24px' }}>
          <Text>DTI Pampanga Show in partnership with Where in Pampanga</Text>
        </div>
        <div style={{ marginBottom: '24px' }}>
          <YoutubeEmbed embedId="Zk_1YX3oWeE" />
        </div>
        <div style={{ marginBottom: '24px' }}>
          <YoutubeEmbed embedId="MDuYxm_zFcE" />
        </div>
        <div style={{ marginBottom: '24px' }}>
          <YoutubeEmbed embedId="6VCmMLjLKSs" />
        </div>
        <div style={{ marginBottom: '24px' }}>
          <YoutubeEmbed embedId="6VCmMLjLKSs" />
        </div>
      </Container>
    </>
  )
}

export default About
