import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>DTI Pasikanan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to DTI Pasikanan
        </h1>
        <Link href="/directory">
          <a>
            <span style={{textDecoration: 'underline'}}>Directory List</span>
          </a>
        </Link>
      </main>

      <footer className={styles.footer}>
          Copyright 2020 DTI / Gulis Digital
      </footer>
    </div>
  )
}

export default Home
