import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Banner, Categories, FeaturedStories, Info } from 'components/landing'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>DTI Pasikanan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <Info />
      <Categories />
      <FeaturedStories />
    </>
  )
}

export default Home
